spring.application.name=Exp2_S4_Grupo3
server.port=8080

# Swagger / OpenAPI config
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
